import React, { useState, useEffect } from 'react';
import { TrendingUp, BarChart3, Lightbulb, RefreshCw } from 'lucide-react';
import './AY2ScoringEngine.css';

const AY2ScoringEngine = () => {
  const [predictedScore, setPredictedScore] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Function to fetch predicted score from backend
  const fetchPredictedScore = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('http://localhost:5001/predict-latest');
      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }
      const data = await response.json();
      setPredictedScore(data.predicted_score);
    } catch (err) {
      setError(err.message || 'Failed to fetch predicted score');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPredictedScore();
  }, []);

  const getScoreColor = (score) => {
    if (score >= 80) return 'excellent';
    if (score >= 70) return 'good';
    if (score >= 60) return 'fair';
    if (score >= 50) return 'poor';
    return 'critical';
  };

  const getScoreLabel = (score) => {
    if (score >= 80) return 'Excellent';
    if (score >= 70) return 'Good';
    if (score >= 60) return 'Fair';
    if (score >= 50) return 'Poor';
    return 'Critical';
  };

  return (
    <div className="ay2-scoring">
      <div className="scoring-header">
        <div className="header-left">
          <h3>AY-2 Circularity Scoring Engine</h3>
          <p>AI-powered sustainability assessment across all production stages</p>
        </div>
        <div className="header-right">
          <div className="ml-note">
            <Lightbulb size={16} />
            <span>Future: XGBoost + SHAP, Autoencoder anomaly detection</span>
          </div>
        </div>
      </div>

      <div className="overall-score-section">
        {loading ? (
          <div className="loading-score">
            <RefreshCw size={48} className="spin" />
            <p>Calculating score...</p>
          </div>
        ) : error ? (
          <div className="error-score">
            <p>Error: {error}</p>
          </div>
        ) : predictedScore !== null ? (
          <div className="score-display">
            <div className="score-circle">
              <div className={`score-value ${getScoreColor(predictedScore)}`}>
                {predictedScore}
              </div>
              <div className="score-label">Predicted Score</div>
            </div>
            <div className="score-details">
              <h4>{getScoreLabel(predictedScore)} Performance</h4>
              <p>
                This score is generated by our AI model based on the latest production stage data from the database.
              </p>
            </div>
          </div>
        ) : (
          <div className="scoring-placeholder">
            <BarChart3 size={48} color="var(--gray-400)" />
            <h3>AY-2 Scoring Engine</h3>
            <p>No prediction available yet</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default AY2ScoringEngine;
